name: 'open-build-src'
description: 'buildSrc Library for build.gradle.kts setup'
author: 'Frogobox'
branding:
  icon: archive
  color: green
inputs:
  myInput:
    description: 'Input to use'
    required: false
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}